## Python Importing Packages

In [1]:
# Importing libraries
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from matplotlib import rcParams
from matplotlib.cm import rainbow

## Lchange

In [33]:
# Importing dataset
data1 = pd.read_csv(r'E:\PycharmProjects\telemetry\change2\Lchange.csv')
data1.head()

,Unnamed: 0,Path,acceleration_x,acceleration_y,acceleration_z,placement_x,placement_y,placement_z,second,Speed
0,0,Lchange,-0.018842,-9.778915,0.141910,0.000004,0.127894,-0.003946,849,22.800875
1,1,Lchange,3.053528,-11.339175,1.049893,-0.228431,0.100745,-0.009538,656,8.029377
2,2,Lchange,0.567177,9.913507,0.318716,-0.022131,0.011083,0.002845,369,0.000000
3,3,Lchange,3.598595,10.094262,-1.747821,0.002806,0.166651,0.088069,1468,3.599888
4,4,Lchange,0.466644,8.914932,3.394867,0.002533,0.005173,0.002060,276,0.000000

In [41]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 10 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   Unnamed: 0      1048575 non-null  int64
 1   Path            1048575 non-null  object
 2   acceleration_x  1048575 non-null  float64
 3   acceleration_y  1048575 non-null  float64
 4   acceleration_z  1048575 non-null  float64
 5   placement_x     1048575 non-null  float64
 6   placement_y     1048575 non-null  float64
 7   placement_z     1048575 non-null  float64
 8   second          1048575 non-null  int64
 9   Speed           1048575 non-null  float64
dtypes: float64(7), int64(2), object(1)
memory usage: 80.0+ MB

In [43]:
data1.describe().round(4)

,Unnamed: 0,acceleration_x,acceleration_y,acceleration_z,placement_x,placement_y,placement_z,second,Speed
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,5.242870e+05,6.740000e-02,4.465100e+00,8.910000e-01,-1.700000e-03,-3.000000e-04,-7.000000e-04,5.326278e+03,8.995700e+00
std,3.026977e+05,1.422100e+00,8.133800e+00,3.253100e+00,1.428000e-01,3.171000e-01,1.408000e-01,1.710627e+06,8.101700e+00
min,0.000000e+00,-3.391850e+01,-4.585820e+01,-7.296210e+01,-2.154000e+01,-2.662000e+01,-1.833830e+01,0.000000e+00,-1.000000e+00
25%,2.621435e+05,-5.100000e-01,-2.109600e+00,-9.332000e-01,-2.670000e-02,-3.000000e-02,-1.880000e-02,2.410000e+02,1.010000e+00
50%,5.242870e+05,5.990000e-02,9.081500e+00,7.734000e-01,-6.000000e-04,2.000000e-04,-1.000000e-04,5.190000e+02,7.514000e+00
75%,7.864305e+05,6.345000e-01,9.710300e+00,2.746200e+00,2.330000e-02,3.130000e-02,1.810000e-02,8.610000e+02,1.546220e+01
max,1.048574e+06,3.408010e+01,5.175890e+01,5.905240e+01,1.353560e+01,1.784090e+01,1.552190e+01,6.193164e+08,4.280730e+01

## Rchange

In [44]:
# Importing dataset
data2 = pd.read_csv(r'E:\PycharmProjects\telemetry\change2\Rchange.csv')

In [47]:
dataset2=data2.filter(['speed','acceleration_y','acceleration_x','acceleration_z','placement_x','placement_y','placement_z'])

In [48]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 10 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   Unnamed: 0      1048575 non-null  int64
 1   Path            1048575 non-null  object
 2   acceleration_x  1048575 non-null  float64
 3   acceleration_y  1048575 non-null  float64
 4   acceleration_z  1048575 non-null  float64
 5   placement_x     1048575 non-null  float64
 6   placement_y     1048575 non-null  float64
 7   placement_z     1048575 non-null  float64
 8   second          1048575 non-null  int64
 9   Speed           1048575 non-null  float64
dtypes: float64(7), int64(2), object(1)
memory usage: 80.0+ MB

## Lturn

In [49]:
# Importing dataset
data3 = pd.read_csv(r'E:\PycharmProjects\telemetry\change2\Lturn.csv')

In [50]:
data3.describe()

,Unnamed: 0,acceleration_x,acceleration_y,acceleration_z,placement_x,placement_y,placement_z,second,Speed
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,5.242870e+05,7.027852e-02,4.449929e+00,8.897359e-01,-1.835220e-03,2.732673e-04,-2.659067e-04,4.145775e+03,9.011960e+00
std,3.026977e+05,1.425795e+00,8.141401e+00,3.255438e+00,1.483018e-01,3.386870e-01,1.448788e-01,1.481449e+06,8.109345e+00
min,0.000000e+00,-3.889260e+01,-3.409708e+01,-6.492276e+01,-1.776152e+01,-7.488861e+01,-2.430107e+01,0.000000e+00,-1.000000e+00
25%,2.621435e+05,-5.072098e-01,-2.435719e+00,-9.359467e-01,-2.668680e-02,-2.999348e-02,-1.887685e-02,2.410000e+02,1.021680e+00
50%,5.242870e+05,6.101074e-02,9.079000e+00,7.750244e-01,-6.256100e-04,2.746580e-04,-5.560000e-05,5.210000e+02,7.533435e+00
75%,7.864305e+05,6.340013e-01,9.708488e+00,2.743755e+00,2.334492e-02,3.137893e-02,1.826666e-02,8.630000e+02,1.549313e+01
max,1.048574e+06,4.006218e+01,5.440584e+01,6.786333e+01,3.983975e+01,4.820572e+01,1.748369e+01,6.193164e+08,3.943035e+01

## Rturn

In [52]:
# Importing dataset
data4 = pd.read_csv(r'E:\PycharmProjects\telemetry\change2\Rturn.csv')

In [53]:
data4.describe()

,Unnamed: 0,acceleration_x,acceleration_y,acceleration_z,placement_x,placement_y,placement_z,second,Speed
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,5.242870e+05,6.781569e-02,4.466073e+00,8.991424e-01,-1.755826e-03,5.221618e-04,-2.987252e-04,6.508671e+03,9.004287e+00
std,3.026977e+05,1.426663e+00,8.130369e+00,3.249382e+00,1.445794e-01,3.540190e-01,1.585487e-01,1.912538e+06,8.108302e+00
min,0.000000e+00,-3.276804e+01,-5.730359e+01,-7.844842e+01,-2.644802e+01,-3.195618e+01,-5.355445e+01,0.000000e+00,-1.719776e+00
25%,2.621435e+05,-5.089782e-01,-2.031598e+00,-9.260130e-01,-2.687807e-02,-2.982741e-02,-1.866861e-02,2.420000e+02,1.010000e+00
50%,5.242870e+05,6.116028e-02,9.081485e+00,7.822235e-01,-6.530070e-04,2.771240e-04,-3.050000e-05,5.200000e+02,7.521385e+00
75%,7.864305e+05,6.346278e-01,9.709213e+00,2.753416e+00,2.337646e-02,3.142718e-02,1.821600e-02,8.630000e+02,1.548000e+01
max,1.048574e+06,2.961647e+01,7.281000e+01,7.331421e+01,1.068810e+01,6.254202e+01,3.383183e+01,6.193165e+08,4.250740e+01

## Straight

In [54]:
# Importing dataset
data5 = pd.read_csv(r'E:\PycharmProjects\telemetry\change2\Straight.csv')

In [55]:
data5.describe()

,Unnamed: 0,acceleration_x,acceleration_y,acceleration_z,placement_x,placement_y,placement_z,second,Speed
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,5.242870e+05,6.828689e-02,4.469311e+00,8.947290e-01,-1.674882e-03,5.410437e-05,-1.536961e-04,2.373283e+03,8.995186e+00
std,3.026977e+05,1.418968e+00,8.129408e+00,3.257305e+00,1.434558e-01,3.438467e-01,1.566063e-01,1.047544e+06,8.100957e+00
min,0.000000e+00,-3.351404e+01,-4.570617e+01,-6.524546e+01,-1.422207e+01,-3.259038e+01,-2.343101e+01,0.000000e+00,-1.000000e+00
25%,2.621435e+05,-5.081238e-01,-2.017841e+00,-9.314606e-01,-2.685665e-02,-2.993240e-02,-1.884460e-02,2.410000e+02,1.012901e+00
50%,5.242870e+05,6.116028e-02,9.083601e+00,7.740000e-01,-6.664540e-04,2.593990e-04,-4.280000e-05,5.190000e+02,7.511251e+00
75%,7.864305e+05,6.344828e-01,9.709685e+00,2.751968e+00,2.325440e-02,3.124477e-02,1.820990e-02,8.620000e+02,1.546000e+01
max,1.048574e+06,3.961567e+01,5.734288e+01,5.198087e+01,1.807407e+01,4.504540e+01,6.630078e+01,6.193158e+08,1.480186e+02

## concatenate dataset

In [56]:
dataset=pd.concat([data1,data2,data3,data4,data5])
dataset
dataset.to_csv("combined.csv")

In [63]:
dataset['class']=dataset['Path'].map({"Lchange":1,"Rchange":2,"Lturn":3,"Rturn":4,"Straight":5})
dataset.tail()

,Unnamed: 0,Path,acceleration_x,acceleration_y,acceleration_z,placement_x,placement_y,placement_z,second,Speed,class
1048570,1048570,Straight,0.258582,10.345661,0.840390,0.011537,-0.001255,0.023616,512,9.517327,5
1048571,1048571,Straight,0.189148,9.950606,-0.351958,0.002797,0.003351,0.003212,87,0.000000,5
1048572,1048572,Straight,-1.877000,9.232000,1.206000,-0.000580,0.006378,-0.018311,1428,0.000000,5
1048573,1048573,Straight,0.112003,-8.539560,-5.068527,-0.014040,0.008440,0.014759,173,1.329445,5
1048574,1048574,Straight,0.735867,-0.232977,-9.837683,-0.057468,-0.010027,-0.052986,1349,20.650000,5

In [58]:
dataset.isnull().sum().sum()

0

## Splitting the dataset(train_test_split)

In [65]:
X = dataset.loc[:,['acceleration_y','acceleration_x','acceleration_z','placement_x','placement_y','placement_z']]
y = dataset.loc[:,'class']

In [66]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [25]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

      acceleration.y  acceleration.x  acceleration.z
4280       -0.001955        0.000561       -1.276849
5898        0.007394       -0.010241       -0.685589
3460       -0.076438       -0.593262        1.396266
1185       -0.047009        0.000060        5.633855
4537        0.001752       -0.004594       -0.810609
...              ...             ...             ...
2649       -0.000922        0.002151       -1.235237
4416       -0.011112       -0.020987        3.316109
9845        0.020553        0.000858       -0.793675
325         0.122777       -0.009376       -0.664839
2732        0.023542        1.126642       -1.090333

[22318 rows x 3 columns]
      acceleration.y  acceleration.x  acceleration.z
699         0.008666       -0.034016       -1.210536
3841       -0.034444        0.264320       -0.425750
9416        0.004401        0.114883        0.019407
1550        0.008386       -0.683002       -0.144081
2511       -0.004552       -0.010880       -0.040655
...              ...             ...             ...
4471       -0.042358       -0.038740        6.191408
1136        0.001632        0.200823       -1.254092
4317       -0.019732        0.000101        0.358348
1170        0.016583       -0.000040       -0.755064
94         -0.117465       -0.184425        8.770552

[9566 rows x 3 columns]
4280    5
5898    1
3460    1
1185    3
4537    5
       ..
2649    2
4416    3
9845    1
325     2
2732    1
Name: class, Length: 22318, dtype: int64
699     5
3841    1
9416    1
1550    1
2511    3
       ..
4471    3
1136    5
4317    4
1170    5
94      4
Name: class, Length: 9566, dtype: int64

## MACHINE LEARNING MODELS

In [70]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 24, metric = 'minkowski', p = 2)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=24, p=2,
                     weights='uniform')

In [71]:
# Plotting a graph for n_neighbors 
from sklearn import metrics
from sklearn.metrics import accuracy_score
y_pred_knn = knn.predict(X_test)
accuracy_knn = accuracy_score(y_test, y_pred_knn)

In [72]:
# Logistic Regression Algorithm
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(random_state = 42)
logreg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

### Making predictions on test dataset

In [73]:
# Making predictions on test dataset
Y_pred_logreg = logreg.predict(X_test)
Y_pred_knn = knn.predict(X_test)

# MODEL EVALUATION

In [31]:
# Evaluating using accuracy_score metric
from sklearn.metrics import accuracy_score
accuracy_logreg = accuracy_score(y_test, Y_pred_logreg)
accuracy_knn = accuracy_score(y_test, Y_pred_knn)

In [74]:
# Accuracy on test set
print("Logistic Regression: " + str(accuracy_logreg * 100))
print("K Nearest neighbors: " + str(accuracy_knn * 100))

Logistic Regression: 33.04411457244407
K Nearest neighbors: 19.97643787157559